Add the parameter `out` to `opq` to select the level of verbosity of the results
ropensci/osmdata pull request #288
Opened 2022-12-06 11:33 UTC by jmaspons

I can replicate the option for `opq_osm_id`, `opq_enclosing` and `opq_around`

2022-12-06 11:49 UTC, jmaspons commented
Checks fail due to a link in the documentation to `osmdata_data_frame` which is not merged yet #285

2022-12-13 15:58 UTC, jmaspons commented
From my side, ready for the merge @mpadge 

P.S.: Don't know why there are no test coverage checks from the gh actions anymore

2022-12-14 09:12 UTC, mpadge requested changes

2022-12-14 09:12 UTC, mpadge commented on R/opq.R
> +        suffix <- gsub ("out( body)*;", paste0 ("out ", out, ";"), suffix)
```suggestion
        suffix <- gsub ("out(\\sbody)*;", paste0 ("out ", out, ";"), suffix)
```

2022-12-14 09:12 UTC, mpadge commented on R/opq.R
> +        suffix <- gsub ("\\);(\\n\\(\\._;>;\\);\\n| )out( body)*;", paste0 ("); out ", out, ";"), suffix)
Why not just redefine `suffix` completely?
```suggestion
        suffix <- paste0 ("); out ", out, ";")
```

2022-12-14 12:17 UTC, mpadge approved these changes

2022-12-14 12:21 UTC, jmaspons commented
Thanks for the review. I have rewritten this part by testing the condition for `has_geometry` adding `nodes_only`, and build the suffix from scratch. This makes the tests fails because they expect that queries with nodes_only have no "body" in the string, which is the default anyway. This limit queries with `nodes_only `and out meta;. I have changed the tests

2022-12-14 14:17 UTC, merged